language: go
go:
  - 1.10.x
addons:
  apt:
    packages:
      - python3
script:
  - "python3 ./build.py -ib"
  - "go test -v ./..."
before_deploy:
  - "go version"
  - "ls -al"
  - "python3 ./build.py -id"
deploy:
  provider: releases
  api_key:
    secure: "Ilde8EWMn9k8KQpOXW1ge6D9xbDSmqSXg8XRe24oavsRCbDE5dPUa1J8RUbsW7vH3Ysutx9Q4h1TyR0zpWIBi9it3FJO0I+PKBKxjAhhfEosHH/TZ7YxTWwcEzUpyMjDzH/BotIMll5ncKkDxvwXowlz4QIT0R0gK1v9kM5qHfedHfl4oX5jLEexRrltLUM2tQvgWmu9m+6OOiqeD7JHkHDeptvvxkI1cm99iNzUczEimZEHNojh9WYlnkcJQ+T+me+csYez4N5Mw+t5yAmHJtfAr2mHG1KsuCCdXZ7Pa3lXGwAsHyjnugKINJpnxmky3cEmJsARDvwS4kVsbsRChuwbgwjTLe9TrK4dikKmQNC6OA4QOeq3HkVK7EQxMOASPACEtGJ/2dRQP0/k1BRALMPfTXzijWf7+czWGMEgS+wLDtcASM4C8elPBp5xrKSsvH3c0/2li7euRuKrnW3d/znBe7pwCX74cOsQx5NPT2xnajRtWPz3dBh+qHo5MCKTFnhXsDRgY0UttVR0T0yXplsx2BQkpF8MpSGydxB3bExLyly9i4m0aStvsYro/lg2uraJlK6KwXt0yuRRPudLhuKyHu6ACZIUzxpUg8Ojw+dVPLyve8oxe7rjjDfKbyDPx4j2jA2SnvOj842+Dj8jmxR9t/JaH4fyaqEcFFcnn74="
  file:
    - overture-darwin-amd64.zip
    - overture-linux-386.zip
    - overture-linux-amd64.zip
    - overture-linux-arm.zip
    - overture-linux-arm64.zip
    - overture-linux-mips-softfloat.zip
    - overture-linux-mips-hardfloat.zip
    - overture-linux-mipsle.zip
    - overture-linux-mips64.zip
    - overture-linux-mips64le.zip
    - overture-windows-386.zip
    - overture-windows-amd64.zip
  skip_cleanup: true
  on:
    tags: true
